### ISSUE TITLE
Add support for npm 9.x + legacy and web format

### ISSUE THREAD

**Issue by george2515** [jenkinsci/pipeline-npm-plugin#95]
### What feature do you want to see added?

When choosing to inject secret into `.npmrc` file, the `_auth` parameter format is not compatible with the default web format npm 9.x + expect. 
More info can be found here:
https://jfrog.com/help/r/artifactory-changes-to-the-login-behavior-in-npm-v9/users-authenticating-with-the-npm-login-command

My suggestion would be to add an optional parameter to `withNPM`, where a user can supply the format of the `_auth` generated in the `.npmrc` file. Something along these lines:

```
withNPM(format: legacy/web/<other>) {   ///defaults to whatever
        sh 'npm install'
}
```

**Comment by jonesbusy** [comment]
Hi,

withNpm only supply config files to the correct location.

I guess you are using with https://plugins.jenkins.io/nodejs/ which provide a format for .npmrc files.

There is an option to enforce NPM+9 format.

I confirm it works, i'm using it with Artifactory has well.

Regards,
